cryptononprofit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib import admin

import main.views
from main.views import ProjectSitemap, ProjectVersionSitemap, UserSitemap, StaticViewSitemap
from django.contrib.sitemaps import views as sitemap_views

sitemaps = {'static': StaticViewSitemap,
            'projects': ProjectSitemap,
            'project-versions': ProjectVersionSitemap,
            'users': UserSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls'))),
    path('admin/defender/', include('defender.urls')),
    # path('email/', include('email_change.urls')),
    path('main/', include('main.urls')),
    path('user/', include('user.urls')),
    path('', main.views.MainPage.as_view(), name='mainpage'),
    path('docs/', include('docs.urls')),
    path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    path('report/', include('report.urls')),
    path('sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.urls import path

import docs.views

app_name = 'docs'
urlpatterns = [
    path('raisers', docs.views.Raisers.as_view(), name='raisers'),
    path('traders', docs.views.Traders.as_view(), name='traders'),
    path('donors', docs.views.Donors.as_view(), name='donors'),
    path('bitcoin-ethereum', docs.views.BitcoinEthereum.as_view(), name='bitcoin-ethereum'),
    path('rules', docs.views.Rules.as_view(), name='rules'),
    path('contract', docs.views.Contract.as_view(), name='contract'),
    path('charter', docs.views.Charter.as_view(), name='charter'),
    path('misc', docs.views.Misc.as_view(), name='misc'),
    path('help', docs.views.Help.as_view(), name='help'),
    path('privacy-policy', docs.views.Privacy.as_view(), name='privacy'),
    path('editorial-guidelines', docs.views.EditorialGuidelines.as_view(), name='editorial-guidelines'),
    path('team', docs.views.Team.as_view(), name='team'),
]

project/urls.py
from django.urls import path, re_path

import project.views

app_name = 'project'
urlpatterns = [
    path('create', project.views.Create.as_view(), name='create'),
    re_path(r'edit/(\d+)', project.views.Edit.as_view(), name='edit'),
    path(r'seo/<int:project_pk>', project.views.SEOView.as_view(), name='seo'),
    re_path(r'view/(\d+)', project.views.Show.as_view(), name='view'),
    re_path(r'view-old/(\d+)', project.views.OldShow.as_view(), name='view-old'),
    re_path(r'activity/(\d+)', project.views.ProjectActivity.as_view(), name='activity'),
    path('list', project.views.List.as_view(), name='list'),
    path('feed', project.views.LatestProjectsMainFeed(), name='feed'),
    path('feed-investments', project.views.LatestProjectsInvestmentsFeed(), name='feed-investments'),
    re_path(r'withdraw/(\d+)', project.views.Withdraw.as_view(), name='withdraw'),
    # re_path(r'change-owner/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),
    re_path(r'change-owner2/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),  # make URL different
]

docs/models.py
from django.db import models

# Create your models here.

docs/views.py
from django.shortcuts import render
from django.views.generic import View

from docs.misc import render_verbatim


class Raisers(View):
    def get(self, request):
        return render(request, 'docs/raisers.html')


class Traders(View):
    def get(self, request):
        return render(request, 'docs/traders.html')


class Donors(View):
    def get(self, request):
        return render(request, 'docs/donors.html')


class BitcoinEthereum(View):
    def get(self, request):
        return render(request, 'docs/bitcoin-ethereum.html')


class Rules(View):
    def get(self, request):
        return render(request, 'docs/rules.html')


class Contract(View):
    def get(self, request):
        return render(request, 'docs/contract.html')


class ContractSource(View):
    def get(self, request):
        return render_verbatim(request, 'docs/Nonprofit.sol', content_type='text/plain')


class Misc(View):
    def get(self, request):
        return render(request, 'docs/misc.html')


class Charter(View):
    def get(self, request):
        return render(request, 'docs/charter.html')


class Privacy(View):
    def get(self, request):
        return render(request, 'docs/privacy.html')


class EditorialGuidelines(View):
    def get(self, request):
        return render(request, 'docs/editorial-guidelines.html')


class Team(View):
    def get(self, request):
        return render(request, 'docs/team.html')


class Help(View):
    def get(self, request):
        return render(request, 'docs/help.html')

docs/templates/docs/bitcoin-ethereum.html
{% extends "main/base.html" %}
{% load static %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:bitcoin-ethereum' %}" />{% endblock %}
{% block title %}Blockchain, Cryptocurrencies, and Crowdfunding{% endblock %}
{% block header %}Blockchain, Cryptocurrencies, <span>and Crowdfunding</span>{% endblock %}
{% block shortheader %}BITCOIN AND ETHERIUM{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:bitcoin-ethereum' %}">BITCOIN AND ETHERIUM DONATIONS/CROWDFUNDING</a></li>
{% endblock %}

{% block content %}
    <img src="img/service/1.jpg" class="img-responsive"
         style="float: left; margin-right:10px; margin-bottom:10px; width: 50%">
    <p>Blockchain—the underlying technology for BitCoin and Etherium—has received widespread acceptance recently and is being used for a number of new applications owing to its security and transparency. One such application is business funding, which also includes creating innovative ways of financing non-profit projects.</p>
    <p>This has been a welcoming change primarily due to a number of problems associated with traditional business crowdfunding that takes one of three forms: bank funding, self-funding, or venture capital. Self-funding was and still remains incredibly limited for most people, bank funding requires positive cash flows along with significant revenues, and venture fund capital hinges on a product or service with mass appeal.</p>
    <p>Also, according to an article published on medium, crowdfunding projects on popular platforms such as Kickstarter and Patreon sometimes fail to provide transparency and act in ways that maximize the interests of the said platforms rather than the users.</p>
    <p>Such factors make it incredibly difficult for both businesses and entrepreneurs to access funding and inhibit growth for products and/or services that have massive potential. Because blockchain is completely transparent, is accessible from anywhere, and makes the funding process safe, it can maximize the probability of success, especially for non-profit initiatives that champion worthy causes and stand to benefit society the most.</p>
    <p>Enter Crypto4NGO: an open-source platform and website designed to help worthy non-profit projects access the financing they deserve. It enables users to create their own unique BitCoin and Etherium-backed cryptocurrencies which can be bought and sold to generate revenue. The service is free to use for both fundraisers and traders/donors and represents an innovative concept with the potential to give life to worthy causes.</p>
{% endblock %}

docs/templates/docs/charter.html
{% extends "main/base.html" %}
{% load static %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:charter' %}" />{% endblock %}
{% block title %}Charter{% endblock %}
{% block header %}<span>Charter</span>{% endblock %}
{% block shortheader %}Charter{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:charter' %}">Charter</a></li>
{% endblock %}

{% block content %}
<p>Ignore all the below. After the US goverment stole $550.46 from me, we are again a nonprofit unregistered in
    Russia, don't want to deal with toxic US.</p>
<blockquote>
    <p>US government stole $550.46 from me.</p>
    <p>I paid $400 to register a 501(c)3 nonprofit in the US that is the right to operate in the US. Now I have no
        person with SSN in the nonprofit and so PayPal locked my $150.46 on a nonprofit account. Total $550.46 stolen
        or cheated (no right for which I paid and no return of borrowed money).</p>
    <p>The funny thing is that I can just stop two scientific projects and the would lose trillions of dollars (in
        addition to what they already lost with their silly behavior).</p>
</blockquote>

<p>crypto4ngo.org (dba CryptoNGO or crypto4ngo) is a project by Victor Porton's Foundation,
    a 501(c)3 nonprofit registered in Colorado, Greeley, CO, United States
    (under control of Victor Lvovich Porton, living in Ashkelon, Israel, an Israel and Russian citizen).</p>
<p>Victor Porton's Foundation is controlled by Victor Porton, currently living in Ashkelon, Israel.</p>
<p>CryptoNGO is a noncommercial project which develops open source software which helps to finance other noncommercial
    organizations (<q>benefactors</q>) and personal noncommercial projects especially of poor people through using
    cryptocurrencies and other means,
    particularly through issuing new cryptocurrencies for financing a particular project.</p>
<p>The service of CryptoNGO is gratis for benefactors.</p>
<p>CryptoNGO supports software for trading by newly issuing currencies in order to finance projects of benefactors effectiviely.</p>
<p>CryptoNGO can pursue in a lawsuite authors of fake projects and other crook acts related with CryptoNGO infrastructure.</p>
{# <p>The CEO (that is Victor Porton) of the organization may block projects which are considered not good for the mankind.</p> #}
<p>Victor Porton is most probably going to create a separate 501(c)3 nonprofit for this project.
    This is not yet necessary because Victor Porton is the sole director with unlimited control rights, yet.</p>
<h3>USA official document references</h3>
<ul>
    <li><a target="_blank" href="https://www.sos.state.co.us/biz/BusinessEntityHistory.do?quitButtonDestination=BusinessEntityDetail&pi1=1&nameTyp=ENT&masterFileId=20151334167&entityId2=20151334167&srchTyp=ENTITY">
        The list of filed documents</a> (at the Colorado Secretary of State site).</li>
    <li>The <a target="_blank" href="{% static 'legal/1023-vpf.pdf' %}">1023 tax exempt form</a> filed to the IRS.</li>
    <li>Tax reporting 990 forms are available <a target="_blank" href="https://www.guidestar.org/profile/47-4102582">here</a>.</li>
</ul>
<h3>Contact data</h3>
<h4>Mailing addresses</h4>
<ul>
    <li>Victor Porton, Shay Agnon 32-29, Ashkelon, Israel, 78640 (preferred)</li>
    <li>Victor Porton,
14350 60th St North,
Suite: 46431,
Clearwater FL. 33760.</li>
</ul>
<h4>Email</h4>
<ul><li>porton@narod.ru</li></ul>
<h4>Phone</h4>
<ul><li>+972-545229306, Victor Porton</li></ul>
{% endblock %}

docs/templates/docs/contract.html
{% extends "main/base.html" %}
{% load include_verbatim %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:contract' %}" />{% endblock %}
{% block title %}Our smart contract{% endblock %}
{% block header %}Our smart contract{% endblock %}
{% block shortheader %}Smart contract{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:contract' %}">Smart contract</a></li>
{% endblock %}

{% block content %}
<h2>Introduction</h2>

<p>When you create a project on with site, you automatically receive so called smart contract.
    (Smart contract is a cryptographically singed short computer program which regulates payments you can make
    with it and payments to you.)</p>

<h2>Holding and transferring tokens</h2>
<p>Our contract associates an amount of your own currency (called <q>tokens</q>) with every Ethereum account in the Net.
    The money can be transferred between accounts.</p>
<p>Your (<q>owner</q>) account is special. It shows in Wallet as containing 10<sup>24</sup> amount of your tokens,
    but behaves as an infinite amount of money (when you withdraw money from your account it remains 10<sup>24</sup>
    no matter how much you withdraw). If somebody sends tokens to your account, it also remains 10<sup>24</sup>
    (does not increase).</p>
<p>There is also calculated total amount of your token in the Net. Your 10<sup>24</sup> are <em>not</em>
    counted in the total amount. So when you withdraw tokens from your account, the total amount of your tokens
    in the Net increases (and it decreases if somebody will send tokens to your account).</p>
<h2 id="formula">Selling tokens for Ether</h2>
<p><em>We are not responsible for malicious users or hackers whose contracts may not conform to this formula.</em></p>
<p>Anyone can send Ether (in fact Ether are like real money) to your contract. If he sends Ether, your contract
    automatically sends him back some tokens.</p>
<p>The amount of tokens sent back is calculated by the formula <i>e</i><sup>2</sup>/(<i>T</i>+<i>e</i>) where <i>T</i> is
    the total amount of Ether received to this token before the purchase and <i>e</i> is the amount of Ether sent
    in this transaction. Note that this formula offers huge discounts to big (<q>wholesale</q>) transactions.</p>
<p>You can withdraw Ether from your contract using the project admin area on your contract page at this site.</p>
{% endblock %}

docs/templates/docs/donors.html
{% extends "main/base.html" %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:donors' %}" />{% endblock %}
{% block title %}For donors{% endblock %}
{% block header %}For <span>donors</span>{% endblock %}
{% block shortheader %}For donors{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:donors' %}">Donors</a></li>
{% endblock %}

{% block content %}
    <img src="img/service/3.jpg" class="img-responsive"
         style="float: left; margin-right:10px; margin-bottom:10px; width: 50%">
    <p>
        [<a href="{% url 'project:list' %}">Projects to donate to</a>]
    </p>
    <p>Crypto4NGO is an online platform that enables people to start and <a href="https://crypto4ngo.org/blog/2019/06/collecting-donations-at-kickstarter-why-should-also-use-cryptongo-for-crowdfunding/">fund their own non-profit projects</a> without having to rely on traditional funding institutions. It also allows traders to create their own unique cryptocurrency. Projects that stand to benefit society the most gain increased exposure and are able to raise a considerable amount of capital in a relatively short period of time. Fund <a href="{% url 'project:list' %}">a project</a> or <a href="{% url 'project:view' 1 %}">CryptoNGO itself</a>.</p>
    <p>Donations will also be used for development and advertisement purposes with the end goal of making the Crypto4NGO initiative a self-sustaining model. Prospective donors can browse through the <strong><a href="{% url 'project:list' %}">Projects page</a></strong> to view current non-profits projects and select ones they believe are most deserving of financial help. Donations made in Ether cryptocurrency are rewarded with the donated project’s own unique cryptocurrency, acting as both contributions to charitable causes and <a href="{% url 'docs:traders' %}">investments</a> at the same time.</p>
    <p>There’s no doubt about it—cryptocurrency is the digital currency of the future. Today, the value of roughly 1,610 cryptocurrencies in existence is valued well over $411 billion, as stated by <a target="_blank" href="https://coinmarketcap.com">CoinMarketCap</a>. Each day, more currencies are created as governments and regulatory bodies attempt to grapple with their immense rise and trade.</p>
    <p>BitCoin and Ethereum, in particular, have enabled certain individuals and organizations to make immense profits. As such, many have shown the desire to donate some of their wealth to worthy causes. While there exist numerous charities that already accept donations in virtual currency, a number of worthy non-profit projects go under the radar.</p>
    <p>Founded by Victor Porton, Crypto4NGO is perhaps the first open-source software and website in the world that helps shed light on deserving non-profit initiatives while assisting members achieve <a href="https://crypto4ngo.org/blog/2019/06/financing-nonprofit-projects-with-new-cryptocurrencies-cryptongo/">financial success</a> via the creation of digital currencies. Through the efforts of Mr. Porton, Crypto4NGO has allowed many aspiring individuals to make changes that they wished to be seen in the world make it a better place for all peoples across the earth.</p>
    <p>Donations can be made through BitCoin or Ether. In addition we support donations by other means (such as credit card in USD or EUR, PayPal, etc.) through external fundraising sites.</p>
{% endblock %}

docs/templates/docs/misc.html
{% extends "main/base.html" %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:misc' %}" />{% endblock %}
{% block title %}Misc{% endblock %}
{% block header %}<span>Misc</span>{% endblock %}
{% block shortheader %}Misc{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:misc' %}">Misc</a></li>
{% endblock %}

{% block content %}
<p>The site is made on <a target="_blank" href="https://bitbucket.org/portonv/cryptononprofit">open-source software</a>,
    written in Python/Django and some Solidity.</p>
{% endblock %}

docs/templates/docs/raisers.html
{% extends "main/base.html" %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:raisers' %}" />{% endblock %}
{% block title %}For money raisers{% endblock %}
{% block header %}Create your own <span>project today!</span>{% endblock %}
{% block shortheader %}Money raisers{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:raisers' %}">Non-Profits</a></li>
{% endblock %}

{% block content %}
    <img src="img/service/5.jpg" class="img-responsive"
         style="float: left; margin-right:10px; margin-bottom:10px; width: 50%">
    <p>[<a href="{% url 'project:create' %}">Create your own project today!</a>]</p>
    <p>Crypto4NGO gathers donations in Ether and BitCoin currencies as well as by other means using links to external fundraisers both for your nonprofit projects (both for organizations and for individuals worldwide) and for itself which it then uses for two main purposes. The first is to enable the website to become a self-sustaining model and the second is to facilitate the exchange of new cryptocurrencies for the benefit of non-profit projects listed on its web page.</p>
    <p>Using this site you can create your own cryptocurrency associated with your nonprofit project, which could increase in price in a virtuous circle of increasing value of your nonprofit organization. You also can <strong>advertise (for free) on this site your fundraiser</strong> from another crowdfunding site. Sometimes it is a way to double your donations.</p>
    <p>If you’re thinking of starting a non-profit project but lack the funds to get it off the ground, then posting it on our website is the best way to go forward. Get in touch with us today to learn more.</p>
    <p>Non-profit initiatives throughout the globe manage to attract a considerable amount of finances. According to the U.S <a target="_blank" href="https://nccs.urban.org/publication/nonprofit-sector-brief-2018">National Center for Charitable Statistics</a>, the non-profit sector contributed around $985 billion to the economy in 2015. That’s around 5.4% of the country’s entire GDP.</p>
    <p>Fact of the matter is, cryptocurrencies have moved beyond just existing as mediums of exchange to become financial investment instruments. This idea has given rise to a concept where you can associate any given cryptocurrencies with NGOs to raise potentially millions of dollars to fund the activities of the organization. When associated with a meaningful cause accepting donations in cryptocurrencies, these cryptocurrencies experience a rise in demand which <a href="https://crypto4ngo.org/blog/2019/06/financing-nonprofit-projects-with-new-cryptocurrencies-cryptongo/">increases the value of the currency</a> itself. In this manner both NGO owners and investors win out since any crypto-investments will be much more highly valued and so will the entire financial resource structure of the NGO.</p>
    <p>The majority of non-profit causes are aimed at improving life both nationally and abroad. There are a number of exceptional non-profit organizations that as of yet, have considerably improved the standard of living for countless individuals. However, there are still other’s that fail to garner sufficient attention required to raise capital and as a consequence, die out over time.</p>
    <p><em>Some users will want to make good, therefore they will use such currencies, what will lead to increasing exchange rates for such currencies, what will lead more users what in turn will increase the exchange rate. This is a virtuous circle of increasing the exchange rate. This may make the cryptocurrencies associated with projects even more profitable than regular cryptocurrencies.</em></p>
    <p>Crypto4NGO is a website as well as open-source software that seeks to make creating and financing non-profit projects easier than ever before. By doing so, it also enables both traders/donors and fundraisers to create their own unique currency and sell it to raise money. This <a href="https://crypto4ngo.org/blog/2019/06/collecting-donations-at-kickstarter-why-should-also-use-cryptongo-for-crowdfunding/">revolutionary approach</a> breaks down the <a href="https://crypto4ngo.org/blog/2019/07/modern-money-is-evil-we-need-new-money/">barriers associated with traditional lending</a> and makes it possible to reach a larger audience—all of which can be done for free.</p>
    <p>In addition to this, you can advertise your own projects through the system where we will handle all marketing efforts.</p>
    <p>Expenses of all the projects listed on the website and the website itself are posted openly to ensure that we can maintain the fullest transparency on all transactions made through us. Donations can be made through Bitcoin or Ether through your crypto-wallets or the donor could make donations through any external fundraising site (for example, with a credit card or PayPal in EUR or USD). Best of all, there is no need to register to donate.</p>
    <p>Crypto4NGO is an open-source software and website where non-profits can create a unique currency to gather necessary funds. Designed to <a href="https://crypto4ngo.org/blog/2019/07/modern-money-is-evil-we-need-new-money/">assist people</a> to affect the change that they wish to see in the world and generate high valuations to increase the efficacy of their efforts, we work day and night to help you achieve your goals.</p>
    <p>Get in touch with us today for more information on our services and how we can help increase the value of your NGOs or your cryptocurrency portfolios. Here’s how the entire system works:</p>
    <p>First you create a new currency (using Ethereum <a target="_blank" href="https://en.wikipedia.org/wiki/Cryptocurrency">cryptocurrency</a>, like a BitCoin but different).</p>
    <p>In this new currency your account is special: It holds infinite amount of money. You promise that you will use that money only for a specific nonprofit project which you describe at this site.</p>
    <p>Next cryptocurrency entrepreneurs may notice your project and begin to do business with your new currency. They may purchase your new currency and you get the compensation in Ether (one of the major cryptocurrencies) and/or they may trade your currency at an exchange.</p>
    <p>If your project is good enough, this may lead to creation virtual money exchanges in Internet, which support your currency. Then you can get any amount (limited by your promised limits) of your currency and change it to for example dollars or Euro.</p>
    <p>You use this money to finance your nonprofit project.</p>
    <p>All this is completely free for you.</p>
    <p>They <a target="_blank" href="http://simondlr.com/post/70089813484/in-the-future-everyone-will-have-their-own">say
        that soon everybody will have his own currency</a>. Not sure about everybody, but every nonprofit project should
        have its own currency.</p>
{% endblock %}

docs/templates/docs/rules.html
{% extends "main/base.html" %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:rules' %}" />{% endblock %}
{% block title %}Rules{% endblock %}
{% block header %}<span>Rules</span>{% endblock %}
{% block shortheader %}Rules{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:rules' %}">Rules</a></li>
{% endblock %}

{% block content %}
<h3>NGO description</h3>
<p>CryptoNGO is a project by Victor Porton's Foundation which supports financing (nonprofit) projects by means
of cryptocurrency, especially by creating a new cryptocurrency for a particular project. We provide a Web site where
anyone can register his projects, in order to receive cryptocurrency for his projects for free.</p>

<p>We attempt to hold a balance between interests of benefactors and investors.</p>

<p>We want to support legal persecution of violators of promises given on our site.</p>

<p>See legal information about Victor Porton's Foundation <a href="{% url 'docs:charter' %}">here</a>.</p>

<p>Money usage: Benefits of CryptoNGO may be used for supporting hosting and backend infrastructure and for advertising
    this site (because adequate amounts of advertising may benefit both benefactors and investors).</p>

<h3>Rules</h3>

{% include 'docs/short_rules.html' %}

<p>We allow financing through our site any kinds of nonprofit projects. It is strongly recommended that all projects
    published at our site are nonprofit. We reserve the right to delete commercial projects.</p>
<p>Projects deemed not to support public good or spam our site may be deleted.</p>
<p>We may want to use all legal means to persecute liars which may push false promises to our site.</p>

<h3>Anti-corporativism</h3>
<p>The founder of this site holds anti-corporativism position. By corporativism we mean that in this
    world most benefits are distributed to corporations rather that to anyone including individual people. This of some
    kind unjust. Therefore CryptoNGO allows all kinds of projects, both personal and institutional. If a project is
    associated with an officially registered nonprofit organization, it is recommended to list the country of
    registration, organization name, and its registration number. Notwithstanding with the above, we may want to use
    all legal means to persecute liars which may push false promises to our site. It is strongly recommended that all
    projects published at our site are nonprofit however (because who would want to support others’
    for-profit projects?)</p>
{% endblock %}

docs/templates/docs/traders.html
{% extends "main/base.html" %}

{% block moreheader %}<link rel="canonical" href="{% url 'docs:traders' %}" />{% endblock %}
{% block title %}For Crypto investors{% endblock %}
{% block header %}For Crypto <span>investors</span>{% endblock %}
{% block shortheader %}For Crypto investors{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'docs:traders' %}">Crypto investors</a></li>
{% endblock %}

{% comment %}
{% block adkeywords %}invest,investment,investments,investing,investor,altcoin,altcoins,get rich{% endblock %}
{% endcomment %}

{% block content %}
<img src="img/service/2.jpg" class="img-responsive"
     style="float: left; margin-right:10px; margin-bottom:10px; width: 50%">
<p>
    [<a href="{% url 'project:list' %}?investment=1">Projects to invest to</a>]
</p>
    <p>Crypto4NGO’s model is unique and one of a kind. It holds the potential to uplift countless <a href="{% url 'project:list' %}?investment=1">non-profit projects</a> (including <a href="{% url 'project:view' 1 %}">CryptoNGO itself</a>) that end up creating a positive change in society. It also facilitates automatic exchange of Ether to our cryptocurrency tokens and is an excellent opportunity for crypto-investors to multiple their capital many times over. You don’t even need to register to invest; you can invest directly through your Ethereum wallet or make <a href="{% url 'docs:donors' %}">donations</a> in BitCoin or Ether or through external fundraisers (for example, through credit cards or PayPal in USD or EUR).</p>
<p>As with any lucrative market, there’s a lot of “noise”, i.e. naysayers who claim that the crypto bubble has already popped. While it’s true that BitCoin is currently at its lowest since 2011, there’s one business principle that many inexperienced commentators fail to grasp: every bear market phase is followed by a bull market which is to say, after every fall there is a rise.</p>
    <p>For the crypto market, this phrase holds particularly true. According to <a target="_blank" href="https://www.ccn.com/72-of-cryptocurrency-investors-plan-to-buy-more-this-year-survey/">CCN Markets</a>, crypto-investors are set to buy more despite the apparent “worsening” trends. That’s not to say that there isn’t room for volatility or bad strategies—it simply requires crypto-investors to start looking for new avenues of investment. By treading a path less explored, investors stand to benefit from riding the early—and particularly high—wave.</p>
<p>Anyone who’s trying to increase a given crypto-investment’s value would do well to make donations in exchange for cryptocurrencies of their choice.</p>
    <p>These increases in valuation follow a set procedure that we’ve written a <a href="https://crypto4ngo.org/blog/2019/06/financing-nonprofit-projects-with-new-cryptocurrencies-cryptongo/">rather comprehensive blog</a> on. Capitalizing on this idea, Crypto4NGO is the ultimate platform to help you raise the valuations of your investment portfolios and help NGOs.</p>
<p>The following are some compelling reasons for traders to also become a part of a Crypto4NGO project:</p>
<ol>
    <li>You will make a help to the mankind using these currencies.</li>
    <li><em>Some users will want to make good, therefore they will use such currencies, what will lead to increasing exchange rates for such currencies, what will lead more users what in turn will increase the exchange rate. This is a virtuous circle of increasing the exchange rate. This may make the cryptocurrencies associated with projects even more profitable that regular cryptocurrencies.</em></li>
</ol>
<p>You could get our tokens either in an exchange or immediately and automatically by sending any amount of Ether to a contract address of a nonprofit project on this site.</p>
<p>The amount of tokens sent back after your Ether transfer is accordingly <a href="{% url 'docs:contract' %}#formula">the formula described here</a>.</p>
<p>Note that as the market grows the price of the token grows; it may probably become more profitable to buy our tokens at an exchange than by sending Ether to the contract address. The formula for the price may limit only the upper bound of the price, as exchanges may probably sell our tokens cheaper.</p>
{% endblock %}