cryptononprofit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib import admin

import main.views
from main.views import ProjectSitemap, ProjectVersionSitemap, UserSitemap, StaticViewSitemap
from django.contrib.sitemaps import views as sitemap_views

sitemaps = {'static': StaticViewSitemap,
            'projects': ProjectSitemap,
            'project-versions': ProjectVersionSitemap,
            'users': UserSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls'))),
    path('admin/defender/', include('defender.urls')),
    # path('email/', include('email_change.urls')),
    path('main/', include('main.urls')),
    path('user/', include('user.urls')),
    path('', main.views.MainPage.as_view(), name='mainpage'),
    path('docs/', include('docs.urls')),
    path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    path('report/', include('report.urls')),
    path('sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.urls import path

import docs.views

app_name = 'docs'
urlpatterns = [
    path('raisers', docs.views.Raisers.as_view(), name='raisers'),
    path('traders', docs.views.Traders.as_view(), name='traders'),
    path('donors', docs.views.Donors.as_view(), name='donors'),
    path('bitcoin-ethereum', docs.views.BitcoinEthereum.as_view(), name='bitcoin-ethereum'),
    path('rules', docs.views.Rules.as_view(), name='rules'),
    path('contract', docs.views.Contract.as_view(), name='contract'),
    path('charter', docs.views.Charter.as_view(), name='charter'),
    path('misc', docs.views.Misc.as_view(), name='misc'),
    path('help', docs.views.Help.as_view(), name='help'),
    path('privacy-policy', docs.views.Privacy.as_view(), name='privacy'),
    path('editorial-guidelines', docs.views.EditorialGuidelines.as_view(), name='editorial-guidelines'),
    path('team', docs.views.Team.as_view(), name='team'),
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'
urlpatterns = [
    path('crypto-affiliate', CryptoAffiliate.as_view(), name='crypto-affiliate'),
    path('ebook-form', EbookView.as_view(), name='ebook-form'),
    path('subscribe-simple', SubscribeView.as_view(), name='subscribe-simple'),
    path('test', TestView.as_view(), name='test')
]

project/urls.py
from django.urls import path, re_path

import project.views

app_name = 'project'
urlpatterns = [
    path('create', project.views.Create.as_view(), name='create'),
    re_path(r'edit/(\d+)', project.views.Edit.as_view(), name='edit'),
    path(r'seo/<int:project_pk>', project.views.SEOView.as_view(), name='seo'),
    re_path(r'view/(\d+)', project.views.Show.as_view(), name='view'),
    re_path(r'view-old/(\d+)', project.views.OldShow.as_view(), name='view-old'),
    re_path(r'activity/(\d+)', project.views.ProjectActivity.as_view(), name='activity'),
    path('list', project.views.List.as_view(), name='list'),
    path('feed', project.views.LatestProjectsMainFeed(), name='feed'),
    path('feed-investments', project.views.LatestProjectsInvestmentsFeed(), name='feed-investments'),
    re_path(r'withdraw/(\d+)', project.views.Withdraw.as_view(), name='withdraw'),
    # re_path(r'change-owner/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),
    re_path(r'change-owner2/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),  # make URL different
]

user/urls.py
from django.urls import path, re_path

import user.views

app_name = 'user'
urlpatterns = [
    path('register', user.views.Register.as_view(), name='register'),
    path('account', user.views.Account.as_view(), name='account'),
    path('amounts', user.views.Amounts.as_view(), name='amounts'),
    re_path(r'profile/(\d+)', user.views.ViewProfile.as_view(), name='profile'),
]

project/models.py
import re

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from ordered_model.models import OrderedModel


def ethereum_address_validator(value):
    if value[0:2].lower() != '0x':
        raise ValidationError("Ethereum address must start from 0x")
    if len(value) != 42:
        raise ValidationError("Ethereum address must consist of 42 characters")
    if not re.match(r'^[0-9a-fA-F]', value):
        raise ValidationError("Ethereum address must be hexadecimal")


class PaymentURL(OrderedModel):
    url = models.URLField("URL")
    title = models.CharField("Site title", max_length=255, blank=False)
    project_version = models.ForeignKey('ProjectVersion', on_delete=models.CASCADE, related_name='payment_urls')

    order_with_respect_to = 'project_version'


class EthereumWallet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    address = models.CharField("Wallet or contract address", max_length=42,
                               validators=[ethereum_address_validator], blank=False)

    class Meta:
        constraints = [
           models.UniqueConstraint(fields=['project', 'address'], name='unique_ethereum_data'),
        ]


TOKEN_RULES = {
    1: "project/contracts/quadratic.html",
}


class ERC20Token(EthereumWallet):
    wallet = models.OneToOneField(EthereumWallet, on_delete=models.CASCADE, primary_key=True)

    contract_symbol = models.CharField("Currency symbol", blank=False, max_length=255,
                                       help_text="Any short string (recommended three capital letters) you may name it")
    contract_name = models.CharField("Currency name", blank=False, max_length=255, help_text="Any name for your new currency")
    owner = models.CharField("Owner account", max_length=42,
                             help_text="The account which controls the contract and on which you may receive money.",
                             validators=[ethereum_address_validator], blank=False)
    rules = models.SmallIntegerField("Contract rules", default=1)


class ProjectImage(models.Model):
    image = models.ImageField(upload_to='project-images/%Y/%m/%d/')


class Project(models.Model):
    disabled = models.BooleanField("Disabled", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    current_ethereum_wallet = models.ForeignKey('EthereumWallet', verbose_name="Ethereum wallet", null=True,
                                                related_name='erc20_wallets', on_delete=models.SET_NULL)

    @property
    def current_erc20_token(self):
        return getattr(self.current_ethereum_wallet, 'erc20token', None) if self.current_ethereum_wallet else None

    # def equal(self, other):
    #     return self.address == other.address

    def last_version(self):
        return ProjectVersion.objects.filter(project=self).order_by('pk').last()

    def get_absolute_url(self):
        return reverse('project:view', args=[self.pk])


class ProjectVersion(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)

    bitcoin_address = models.CharField("BitCoin address for donations (optional)", max_length=35, blank=True, null=True)

    title = models.CharField("Project title", max_length=200, blank=False)
    description = models.TextField("Project description", blank=False)
    money_usage = models.TextField("Allowed use of money", blank=True)
    allow_advertisement = models.BooleanField("Allowed to use money for advertisements")
    allow_press_releases = models.BooleanField(
        "Allowed to use money for press releases (overrides \"allowed to use money for advertisements\")")

    url = models.URLField("Related link", blank=True)

    OWNERSHIP_PERSONAL = 0
    OWNERSHIP_UNREGISTERED = 1
    OWNERSHIP_REGISTERED = 2
    OWNERSHIP_CHOICES = (
        (OWNERSHIP_PERSONAL, 'personal'),
        (OWNERSHIP_UNREGISTERED, 'unregistered nonprofit'),
        (OWNERSHIP_REGISTERED, 'registered nonprofit'),
    )
    ownership = models.SmallIntegerField("Project ownership kind", choices=OWNERSHIP_CHOICES)

    country = CountryField("Country", blank=True)
    organization_name = models.CharField("Organization name", max_length=255, blank=True)
    organization_number = models.CharField("Organization registration number", max_length=20, blank=True)

    project_image = models.ForeignKey('ProjectImage', null=True, on_delete=models.SET_NULL)

    def clean(self):
        if self.allow_advertisement:
            self.allow_press_releases = True
        if self.ownership == ProjectVersion.OWNERSHIP_PERSONAL:
            self.organization_name = ''
        if self.ownership != ProjectVersion.OWNERSHIP_REGISTERED:
            self.organization_number = ''
        if self.organization_number != '' and self.country is None:
            raise ValidationError('If you specify organization number, you must also specify the country.')

    # Should be called after clean()
    def equal(self, other):
        return \
            self.bitcoin_address == other.bitcoin_address and \
            self.title == other.title and \
            self.description == other.description and \
            self.money_usage == other.money_usage and \
            self.allow_advertisement == other.allow_advertisement and \
            self.allow_press_releases == other.allow_press_releases and \
            self.url == other.url and \
            self.ownership == other.ownership and \
            self.country == other.country and \
            self.organization_name == other.organization_name and \
            self.organization_number == other.organization_number and \
            self.project_image == other.project_image and \
            self._equal_payment_urls(other)

    def _equal_payment_urls(self, other):
        # One equality side may be a QuerySet and another list.
        # TODO: No need to retrieve and compare the full lists.
        return list(self.payment_urls_data) == list([{'url': p.url, 'title': p.title} for p in other.payment_urls.all()])

    def get_absolute_url(self):
        return reverse('project:view-old', args=[self.pk])

report/models.py
from django.db import models


class Withdrawal(models.Model):
    time = models.DateTimeField("Date and time of withdrawal", auto_now_add=True)
    project = models.ForeignKey('project.Project', verbose_name="Project", on_delete=models.CASCADE)
    # amount = models.DecimalField("Amount (in Ether)", max_digits=78, decimal_places=18)  # may fail with big numbers
    amount = models.CharField("Amount (in Ether)", max_length=79, blank=False)
    purpose = models.TextField("How going to use the money", blank=False)
    wallet = models.CharField(max_length=42, blank=True, help_text="Leave empty to use the owner wallet")

project/templates/project/edit_project.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
{% if mode == 'create' %}Create{% else %}Edit{% endif %} project
{% endblock %}
{% block header %}
{% if mode == 'create' %}Create{% else %}Edit{% endif %} project
{% endblock %}
{% block shortheader %}
{% if mode == 'create' %}Create{% else %}Edit{% endif %} project
{% endblock %}
{# TODO #}
{#{% block breadcrumbs %}#}
{#    <li><a href="{% url '' %}"></a></li>#}
{#{% endblock %}#}

{% block scripts %}
    <link rel="stylesheet" href="/static/ui-loader/loader.min.css" />
    {{ form.media }}
    <script src="{% static 'web3/web3.min.js' %}"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
    {{ symbol_form.media }}
    <style>
        .hidden { display: none }
        .note-toolbar.panel-heading { z-index: auto !important; }
    </style>
    <script>
        function init_wallet() {
            window.web3.eth.getAccounts(function (err, accounts) {
                var html = $.map(accounts, function(id) {
                    return "<option>" + id + "</option>";
                });
                $('#id_owner').html(html.join());
            });
        }

        $(function() {
          $('#id_description, #id_money_usage').summernote({
              toolbar: [
                  // [groupName, [list of button]]
                  ['style', ['bold', 'italic', 'underline', 'clear']],
                  ['font', ['strikethrough', 'superscript', 'subscript']],
                  ['fontsize', ['fontsize']],
                  ['color', ['color']],
                  ['para', ['style', 'paragraph', 'ol', 'ul']],
                  ['insert', ['link', 'picture', 'video', 'table', 'hr']],
                  ['view', ['fullscreen', 'undo', 'redo', 'help']],
              ]
          });
        });

        $(function() {
            $('#id_allow_advertisement').click(on_change_advertisement);
            $('[name=ownership]').click(on_change_ownership);
            on_change_advertisement();
            on_change_ownership();
            // Disallow conditions downgrade
        {% if mode != 'create' %}
            if(!$('#id_allow_advertisement').is(":checked"))
                $('#id_allow_advertisement').prop('disabled', true);
            if(!$('#id_allow_press_releases').is(":checked"))
                $('#id_allow_press_releases').prop('disabled', true);
        {% endif %}
        {% if symbol_form.stage.value == '1' %}
            xsubmit();
        {% endif %}
        });

        function xsubmit() {
            $('[type=submit]').prop('disabled', true);
            $('#dimmer').css('display', 'block');
            // Call deploy() after both abi and bytecode load
            if(abi && bytecode) { // already loaded
                deploy();
                return;
            }
            $.get('/static/generated/abi.json', function(_abi) {
                abi = _abi;
                deploy();
            }, 'json');
            $.get('/static/generated/bytecode.dat', function(_bytecode) {
                bytecode = _bytecode;
                deploy();
            }, 'text');
        }

        function xconfirm() {
            if(!$('#id_confirm').is(':checked')) return true; // allow the browser handle this missing checkbox
            return confirm('Sure to {% if mode == 'create' %}create{% else %}update{% endif %} project with this data?');
        }
    </script>
{% endblock %}

{% block content %}

<div id="dimmer" class="ui segment" style="position:fixed; left:0px; top:0px; width:100%; height:100%; z-index:100; display:none">
  <div class="ui dimmer" style="position:fixed; width:100%; height:100%; background:gray">
    <div class="ui massive text loader">Creating smart contract</div>
  </div>
  <p></p>
</div>

{% if disabled %}
<p><strong style="color:red">This project is disabled.</strong>
    To re-enable it <a href="{% url 'project:view' project_pk %}">see here</a>.</p>
{% endif %}

{% include 'main/errors.html' %}
<form action="" method="post" enctype='multipart/form-data' onkeypress="return event.keyCode != 13;"
      id="main_form"
      onsubmit="accomplish_deploy()">
    {% csrf_token %}
    <table>
    {{ symbol_form.as_table }}
    {{ form.as_table }}
    {{ confirm.as_table }}
    </table>
    <br />
    {% include 'docs/short_rules.html' %}
    <p>See more <a href="{% url 'docs:rules' %}">here</a>.</p>
    <p>
    {% if mode == 'create' %}
    <input type="submit" value="Create project" onclick="return xconfirm()" />
    {% else %}
    <input type="submit" value="Change project" onclick="return xconfirm()" />
    {% endif %}
    </p>
</form>

<section id="quadratic_popup" class="popup" style="display: none">
    {% include 'project/contracts/quadratic.html' %}
</section>

<div id="id_ask_rules" title="Specify contract type" style="display: none">
    <p><label><input type="radio" id="id_rules_choice_0" name="rules_choice" value="0" checked="checked" /> Unknown</label></p>
    <p><label><input type="radio" id="id_rules_choice_1" name="rules_choice" value="1" /> Quadratic</label>
        (<a href="#" class="popup-link" style="color: blue"
            onclick="$('#quadratic_popup').dialog({modal: true, position: {of: '#id_ask_rules', at: 'left top', my: 'left+50 top+50'}}); return false">formula</a>)</p>
    <p><strong class="red">Choosing an option is legally binding!</strong>
        If you are not completely sure that your contract already belongs to a certain type, choose "unknown".</p>
</div>
{% endblock %}

{% block scripts2 %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>
    <script src="{% static 'myweb3.js' %}"></script>
    <script src="{% static 'edit_project.js' %}"></script>
{% endblock %}

project/templates/project/feed_item.html
{{description}}

<h2>Donate</h2>

<ul>
    {% for pair in version.payment_urls.all %}
    <li><strong><a target="_blank" href="{{ pair.url }}">{{ pair.title }}</a></strong></li>
    {% endfor %}
{% if wallet %}
    <li><strong>Ether</strong>&nbsp;<a href="ethereum:{{wallet.address}}">{{wallet.address}}</a>
        {% if erc20 %}(smart contract {{erc20.contract_symbol}} {{erc20.contract_name}}){% endif %}
    </li>
{% endif %}
    {% if version.bitcoin_address %}
    <li><strong>BitCoin</strong>&nbsp;<a href="bitcoin:{{version.bitcoin_address}}">{{version.bitcoin_address}}</a></li>
    {% endif %}
</ul>

<dl>
    <dt>User</dt>
    <dd><p><a href="{{ settings.SITE_URL }}{% url 'user:profile' project.user.pk %}">{{project.user.username}}</a></p></dd>
    <dt>Allowed uses of money</dt>
    <dd>{{allowed_use}}</dd>
    <dt>Allowed using money for advertisment</dt>
    <dd><p>{{version.allow_advertisement}}</p></dd>
    <dt>Allowed using money for press releases</dt>
    <dd><p>{{version.allow_press_releases}}</p></dd>
    <dt>URL</dt>
    <dd><p><a href="{{version.url}}">{{version.url}}</a></p></dd>
    <dt>Ownership</dt>
    <dd><p>{{ownership}}</p></dd>
    <dt>Country</dt>
    <dd><p>{{version.country.name}}</p></dd>
    <dt>Organization name</dt>
    <dd><p>{{version.organization_name}}</p></dd>
    <dt>Organization number</dt>
    <dd><p>{{version.organization_number}}</p></dd>
</dl>

project/templates/project/list.html
{% extends "main/base.html" %}

{% block moreheader %}
    <meta name="robots" content="noindex"/>
    <link rel="canonical" href="{% url 'project:list' %}?page=
            {{ page }}{% if request.GET.investment == '1' %}&investment=1{% endif %}"/>
{% endblock %}
{% block title %}Projects list{% endblock %}
{% block header %}Projects list{% endblock %}
{% block shortheader %}Projects list{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'project:list' %}?page=
            {{ page }}{% if request.GET.investment == '1' %}&investment=1{% endif %}">Projects</a></li>
{% endblock %}

{% block scripts %}
    <style>
        ul {
            margin: 0px;
            padding: 0px;
        }

        li {
            list-style: none
        }

        ul.list-item li {
            transition: .3s;
            margin: 40px 0px;
        }

        ul.list-item li:hover {
            box-shadow: 0px 0px 10px whitesmoke;
        }

        ul.list-item li h2 a {
            font-size: 30px;
            text-decoration: none;
            font-weight: bold;
        }

        ul.list-item li p {
            font-size: 16px;
            margin: 10px;
            text-align: justify;
        }

        ul.list-item li p a.read-more {
            padding: 7px 10px;
            text-decoration: none;
            background-color: #FF9F1A;
            color: white;
            margin-top: 5px;
            display: inline-block;
        }

        ul.list-item li img {
            display: block;
            margin: 10px auto;
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}

    {% if request.GET.investment == '1' %}
        <p>Showing only projects with investments.
            <nav><a href="{% url 'project:list' %}">Return</a></nav>
        </p>
    {% else %}
        <p>
            <nav><a href="{% url 'project:list' %}?investment=1">Show only projects that I can invest into</a></nav>
        </p>
    {% endif %}

    {% include 'main/paginator_template.html' %}

    <ul class="list-item">
        {% for v in versions %}
            <li>
                <div class="row">
                    <div class="col-sm-5">
                        {% if v.project_image %}
                            <a href="{% url 'project:view' v.project.pk %}">
                                <img src="{{ v.project_image.image.url }}" alt="{{ v.title }}"
                                     style="width: 100%; max-height: 230px; object-fit: cover">
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-sm-7">
                        <h2><a href="{% url 'project:view' v.project.pk %}">{{ v.title }}</a></h2>
                        <p>{{ v.short_description }}<br>
                            <a href="{% url 'project:view' v.project.pk %}" class="read-more">Read More</a></p>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>

    {% include 'main/paginator_template.html' %}

{% endblock %}

project/templates/project/payment_url_editor.html
<div {% include "django/forms/widgets/attrs.html" %}>
    <p>
        <i class="fa fa-sort handle"></i>
        URL: <input type="url" name="{{ widget.name }}_url" value="{{ widget.payment_url }}" style="width: auto">
        Site title: <input type="title" name="{{ widget.name }}_title" value="{{ widget.title }}">
        <input type="button" value="Delete" onclick="if(window.confirm('Delete URL?')) $(this).parent().remove()">
    </p>
</div>

project/templates/project/payment_urls_editor.html
<div class="urls_editor" {% include "django/forms/widgets/attrs.html" %}>
    <ul style="margin: 0">
        <li style="display: none" id="id_{{ widget.name }}_dummy">{{ empty_value }}</li>
    </ul>
    <script>
    {% for pair in widget.value %}
    payment_urls_add('{{ widget.name }}', '{{ pair.url|escapejs }}', '{{ pair.title|escapejs }}');
    {% endfor %}
    </script>
    <div><input type="button" value="Add" onclick="payment_urls_add('{{ widget.name }}', '', '')"></div>
</div>

project/templates/project/seo.html
{% extends "main/base.html" %}

{% block title %}Advertise your project{% endblock %}
{% block header %}Advertise your project{% endblock %}
{% block shortheader %}Advertise{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'project:list' %}?page={{ page }}{% if request.GET.investment == '1' %}&investment=1{% endif %}">Advertise</a></li>
{% endblock %}

{% block content %}

    <p>You've created <a href="{% url 'project:view' project_pk %}">your project</a>. Now to earn money you need to advertise it.</p>

    <p>Special service to advertise a crowdfunding project:</p>

    <p><a href="https://app.krowdster.co/ref/SyO1oNNREEo0" target="_blank"><img src="https://app.krowdster.co/img/banners/supporters/300x250-supporters.gif" /></a></p>

    <p>Use full suite of products for every need. Link Building, Guest Post services, Content Creation, RankTracker, CitationCleanup, OnPage Optimization, LockMyBrand, Ecommerce Product descriptions, Syndication services and other managed SEO services:</p>

    {# They don't provide backlinks. #}
    {# <p><a href="//www.semrush.com/sem/?ref=3838230371&refer_source=&utm_source=berush&utm_medium=promo&utm_campaign=banner" title="SEMrush" target="_blank"><img src="https://t.myvisualiq.net/impression_pixel?r=000&et=i&ago=212&ao=882&aca=affiliate_link&si=affiliate_site&ci=banner&pi=&ad=-4&advt=3838230371&chnl=-4&vndr=1316&sz=9323&u=336x280-grey-en&pt=i"><img src="https://tapestry.tapad.com/tapestry/1?ta_partner_id=950&ta_redirect=https%3A%2F%2Ft.myvisualiq.net%2Fsync%3Fprid%3D1001%26ao%3D0%26pruuid%3DTAPAD_%24%7BIDS%3Akey%7D"><img src="//www.berush.com/static/berush/banners/grey/336x280/336x280_en.png" alt="SEMrush" /></a></p> #}

    <p><a href="https://www.thehoth.com/link-building-service/?aff=3P35" target="_blank" rel="noreferrer"><img border="0" src="https://www.thehoth.com/downloads/ads2018/affiliate-portal-linkbuilding-1.png" alt=""></a></p>

{% endblock %}

project/templates/project/withdraw.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Withdraw Ether{% endblock %}
{% block header %}Withdraw Ether{% endblock %}
{% block shortheader %}Withdraw Ether{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'project:withdraw' version.project.pk %}">Withdraw</a></li>
{% endblock %}

{% block scripts %}
    <link rel="stylesheet" href="/static/ui-loader/loader.min.css" />
    {{ form.media }}
    <script>
        var abi = undefined;

        function undim(e) {
            alert(e);
            $('#dimmer').css('display', 'none');
            $('#pay_btn').prop('disabled', false);
        }

        function withdraw() {
            $('#dimmer').css('display', 'block');
            try {
                var contract = window.web3.eth.contract(abi);
                var contractInstance = contract.at('{{erc20.address}}');
                var address = $('#id_wallet').val();
                var amount = $('#id_amount').val();
                if(address == "") address = '0x0'; // use owner account
                amount = web3.toWei(amount, 'ether');
                contractInstance.withdrawEther.sendTransaction(address, amount, {from: '{{erc20.owner}}'}, function(error, result) {
                    if(error) {
                        undim(error);
                        return;
                    }
                    $('#id_done').val('1');
                    $('#main_form').submit();
                });
            }
            catch(e) { undim(e); }
        }

        function xsubmit() {
            $('#pay_btn').prop('disabled', true);
            $('#dimmer').css('display', 'block');
            if(abi) // already loaded
                withdraw();
            else
                $.get('/static/generated/abi.json', function(_abi) {
                    abi = _abi;
                    withdraw();
                }, 'json');
        }

        {% if stage == 1 %}
        $(function() {
            myweb3_init(xsubmit);
        });
        {% else %}
        $(function() {
            myweb3_init(function(){});
        });
        {% endif %}
    </script>
{% endblock %}

{% block content %}

<div id="dimmer" class="ui segment" style="position:fixed; left:0px; top:0px; width:100%; height:100%; z-index:100; display:none">
  <div class="ui dimmer" style="position:fixed; width:100%; height:100%; background:gray">
    <div class="ui massive text loader">Transferring money</div>
  </div>
  <p></p>
</div>

<p>After you withdraw, you will need to <a href="{% url 'main:crypto-affiliate' %}">sell Ether</a>.</p>

<p><b>Project</b>: {{ version.title }}</p>

{% include 'main/errors.html' %}
<form action="" method="post" onkeypress="return event.keyCode != 13;"
      id="main_form">
    {% csrf_token %}
    <input type="hidden" name="done" id="id_done" />
    <table>
    {{ form.as_table }}
    </table>
    <p><strong>You must use withdrawn money only for the project.</strong>
        Your money usage will be displayed publicly.</p>
    <p>
    <input id="pay_btn" type="submit" value="Pay"  onclick="return confirm('Withdraw money?');" />
    </p>
</form>

{% endblock %}

{% block scripts2 %}
    <script src="{% static 'web3/web3.min.js' %}"></script>
    <script src="{% static 'myweb3.js' %}"></script>
{% endblock %}