cryptononprofit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib import admin

import main.views
from main.views import ProjectSitemap, ProjectVersionSitemap, UserSitemap, StaticViewSitemap
from django.contrib.sitemaps import views as sitemap_views

sitemaps = {'static': StaticViewSitemap,
            'projects': ProjectSitemap,
            'project-versions': ProjectVersionSitemap,
            'users': UserSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls'))),
    path('admin/defender/', include('defender.urls')),
    # path('email/', include('email_change.urls')),
    path('main/', include('main.urls')),
    path('user/', include('user.urls')),
    path('', main.views.MainPage.as_view(), name='mainpage'),
    path('docs/', include('docs.urls')),
    path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    path('report/', include('report.urls')),
    path('sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.urls import path

import docs.views

app_name = 'docs'
urlpatterns = [
    path('raisers', docs.views.Raisers.as_view(), name='raisers'),
    path('traders', docs.views.Traders.as_view(), name='traders'),
    path('donors', docs.views.Donors.as_view(), name='donors'),
    path('bitcoin-ethereum', docs.views.BitcoinEthereum.as_view(), name='bitcoin-ethereum'),
    path('rules', docs.views.Rules.as_view(), name='rules'),
    path('contract', docs.views.Contract.as_view(), name='contract'),
    path('charter', docs.views.Charter.as_view(), name='charter'),
    path('misc', docs.views.Misc.as_view(), name='misc'),
    path('help', docs.views.Help.as_view(), name='help'),
    path('privacy-policy', docs.views.Privacy.as_view(), name='privacy'),
    path('editorial-guidelines', docs.views.EditorialGuidelines.as_view(), name='editorial-guidelines'),
    path('team', docs.views.Team.as_view(), name='team'),
]

project/urls.py
from django.urls import path, re_path

import project.views

app_name = 'project'
urlpatterns = [
    path('create', project.views.Create.as_view(), name='create'),
    re_path(r'edit/(\d+)', project.views.Edit.as_view(), name='edit'),
    path(r'seo/<int:project_pk>', project.views.SEOView.as_view(), name='seo'),
    re_path(r'view/(\d+)', project.views.Show.as_view(), name='view'),
    re_path(r'view-old/(\d+)', project.views.OldShow.as_view(), name='view-old'),
    re_path(r'activity/(\d+)', project.views.ProjectActivity.as_view(), name='activity'),
    path('list', project.views.List.as_view(), name='list'),
    path('feed', project.views.LatestProjectsMainFeed(), name='feed'),
    path('feed-investments', project.views.LatestProjectsInvestmentsFeed(), name='feed-investments'),
    re_path(r'withdraw/(\d+)', project.views.Withdraw.as_view(), name='withdraw'),
    # re_path(r'change-owner/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),
    re_path(r'change-owner2/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),  # make URL different
]

user/urls.py
from django.urls import path, re_path

import user.views

app_name = 'user'
urlpatterns = [
    path('register', user.views.Register.as_view(), name='register'),
    path('account', user.views.Account.as_view(), name='account'),
    path('amounts', user.views.Amounts.as_view(), name='amounts'),
    re_path(r'profile/(\d+)', user.views.ViewProfile.as_view(), name='profile'),
]

user/models.py
import django.contrib.auth.models
from django.db import models
from django.urls import reverse


class User(django.contrib.auth.models.AbstractUser):
    ssh_pubkey = models.TextField("SSH public key", help_text="Leave empty if not sure", blank=True)
    pgp_pubkey = models.TextField("PGP (mail) public key", help_text="Leave empty if not sure", blank=True)
    show_email = models.BooleanField("Show email publicly", default=False)
    show_keys = models.BooleanField("Show public keys publicly", default=False)

    def get_absolute_url(self):
        return reverse('user:profile', args=[self.pk])


class Subscriber(models.Model):
    email = models.EmailField("Email", unique=True)
    fullname = models.CharField("Full name", max_length=100)

    subscribed = models.BooleanField("Subscribe me to the mailing list",
                                     help_text="The mailing list is low-volume.",
                                     db_index=True)
    subscribed_projects = models.BooleanField("Subscribe me to project updates",
                                              db_index=True)

    investor = models.BooleanField("Am I an investor?", default=False)
    donor = models.BooleanField("Am I a donor?", default=False)
    nonprofit = models.BooleanField("Am I a nonprofit project owner?", default=False)

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget

from user.models import User


class MyUserCreationForm(UserCreationForm):
    required_css_class = 'required'

    captcha = ReCaptchaField(widget=ReCaptchaWidget())
    class Meta:
        model = User
        fields = ['username',
                  'password1',
                  'password2',
                  'email',
                  'first_name',
                  'last_name',
                  'ssh_pubkey',
                  'pgp_pubkey',
                  'show_email',
                  'show_keys',
                  'captcha']


class AccountForm(ModelForm):
    required_css_class = 'required'

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['email'].required = True

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'ssh_pubkey', 'pgp_pubkey', 'show_email', 'show_keys']
        required = ['username']

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib.auth import login, authenticate

from project.models import Project
from user.forms import MyUserCreationForm, AccountForm
from user.models import User


class Register(View):
    def get(self, request):
        form = MyUserCreationForm()
        return render(request, 'user/register.html', {'form': form})

    def post(self, request):
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('project:create')
        return render(request, 'user/register.html', {'form': form})


class Account(LoginRequiredMixin, View):
    def get(self, request):
        form = AccountForm(instance=request.user)
        return render(request, 'user/account.html', {'form': form, 'user_pk': request.user.pk})

    def post(self, request):
        form = AccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return render(request, 'user/account.html', {'form': form, 'user_pk': request.user.pk})


class ViewProfile(View):
    def get(self, request, user_pk):
        user = get_object_or_404(User, pk=user_pk)
        projects = Project.objects.filter(user=user_pk).order_by('-pk').only('pk', 'disabled')
        versions = [p.last_version() for p in projects]
        return render(request, 'user/profile.html', {'user': user, 'versions': versions})


class Amounts(LoginRequiredMixin, View):
    def get(self, request):
        h = Project.objects.filter(user=request.user.pk).order_by('-pk').only('pk', 'disabled')
        projects = [(i, h[i], h[i].last_version()) for i in range(len(h))]  # TODO: inefficient
        return render(request, 'user/amounts.html', {'user': request.user, 'projects': projects})

user/templates/user/account.html
{% extends "main/base.html" %}

{% block title %}User account{% endblock %}
{% block header %}User account{% endblock %}
{% block shortheader %}Account{% endblock %}

{% block content %}

{% include 'main/errors.html' %}

{# <p><a href="{% url 'email:email_change' %}">Change email</a></p> #}

<p>
    <a href="{% url 'user:profile' user_pk %}">Public profile</a> |
    <a href="{% url 'user:amounts' %}">Earned amounts</a>
</p>

<form method="post" action="">
{% csrf_token %}
<table>
{{form}}
</table>
<input type="submit" value="Save"/>
</form>

{% endblock %}

user/templates/user/amounts.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}User's projects{% endblock %}
{% block header %}User's projects{% endblock %}
{% block shortheader %}User's projects{% endblock %}

{% block css %}
{% endblock %}

{% block scripts %}
<script>
var contracts = [
    {% for i, project, version in projects %}
    '{% if project.current_ethereum_wallet %}{{ project.current_ethereum_wallet.address }}{% endif %}',
    {% endfor %}
];

function renderOne(i) {
    return function(error, result) {
        $('#p'+i).text(window.web3.fromWei(result) + ' ETH');
    }
}

function render() {
    for(var i in contracts) {
        if(contracts[i] != '')
            window.web3.eth.getBalance(contracts[i], renderOne(i));
        else
            $('#p'+i).text('none');
    }
}

$(function() {
    myweb3_init(render);
});
</script>
{% endblock %}

{% block content %}

<p>User: <a href="{% url 'user:account' %}">{{user.username}}</a></p>

{% if projects %}
<p>This page does not work with Mist 0.11.1. Use MetaMask instead.</p>
<table>
    <tr><th>Project</th><th>Contract balance</th></tr>
    {% for i, project, version in projects %}
    <tr>
        <td>
            <a href="{% url 'project:view' project.pk %}">{{ version.title }}</a>
            {% if project.disabled %}
            (disabled)
            {% endif %}
        </td>
        <td id="p{{i}}">loading...</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>No projects for this user.</p>
{% endif %}

{% endblock %}

{% block scripts2 %}
<script src="{% static 'myweb3.js' %}"></script>
{% endblock %}

user/templates/user/profile.html
{% extends "main/base.html" %}

{% block css %}
textarea { width: 100% }
{% endblock %}

{% block moreheader %}<link rel="canonical" href="{% url 'user:profile' user.pk %}" />{% endblock %}
{% block title %}User {{user.username}}{% endblock %}
{% block header %}User {{user.username}}{% endblock %}
{% block shortheader %}User {{user.username}}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'user:profile' user.pk %}">User</a></li>
{% endblock %}

{% block content %}

<h2>User's projects</h2>

{% if versions %}
<ul>
{% for v in versions %}
    <li><a href="{% url 'project:view' v.project.pk %}">{{v.title}}</a>
        {% if v.project.disabled %}(disabled){% endif %}</li>
{% endfor %}
</ul>
{% else %}
<p>No projects</p>
{% endif %}

<h2>User info</h2>

<dl>
    <dt>Username</dt>
    <dd><p>{{user.username}}</p></dd>
    <dt>First name</dt>
    <dd><p>{{user.first_name}}</p></dd>
    <dt>Last name</dt>
    <dd><p>{{user.last_name}}</p></dd>
    <dt>Email</dt>
    <dd>
        <p>
            {% if user.show_email %}<a href="mailto:{{user.email}}">{{user.email}}</a>{% else %}n/a{% endif %}
        </p>
    </dd>
    <dt>SSH public key</dt>
    <dd>
        <p>
            {% if user.show_keys and user.ssh_pubkey != '' %}
            <textarea readonly="readonly">{{user.ssh_pubkey}}</textarea>
            {% else %}
            n/a
            {% endif %}
        </p>
    </dd>
    <dt>PGP public key</dt>
    <dd>
        <p>
            {% if user.show_keys and user.pgp_pubkey != '' %}
            <textarea readonly="readonly">{{user.pgp_pubkey}}</textarea>
            {% else %}
            n/a
            {% endif %}
        </p>
    </dd>
</dl>

{% endblock %}

user/templates/user/register.html
{% extends "main/base.html" %}

{% block title %}User registration{% endblock %}
{% block header %}User registration{% endblock %}
{% block shortheader %}User registration{% endblock %}
{% block scripts %}
<script async src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block content %}

{% include 'main/errors.html' %}

<p>Already have an account? <a href="{% url 'login' %}">Login</a></p>

<form method="post" action="">
{% csrf_token %}
<table>
{{form}}
</table>
<input type="submit" value="Create user"/>
</form>

<p>You are <em>not</em> required to enter first and last name.
    Moreover you may choose not to enter them if you do not want your financial operations to be associated with
    your name. (This may help to save you from hackers, for example.)</p>

<p>By registering you agree to receive emails (only rare important ones) about site updates and likewise stuff.
    In no event we will distribute your email to spammers.</p>

{% endblock %}