contact/urls.py
from django.urls import path

import contact.views

app_name = 'contact'
urlpatterns = [
    path('contact', contact.views.ContactFormView.as_view(), name='contact'),
]

cryptononprofit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.contrib import admin

import main.views
from main.views import ProjectSitemap, ProjectVersionSitemap, UserSitemap, StaticViewSitemap
from django.contrib.sitemaps import views as sitemap_views

sitemaps = {'static': StaticViewSitemap,
            'projects': ProjectSitemap,
            'project-versions': ProjectVersionSitemap,
            'users': UserSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls'))),
    path('admin/defender/', include('defender.urls')),
    # path('email/', include('email_change.urls')),
    path('main/', include('main.urls')),
    path('user/', include('user.urls')),
    path('', main.views.MainPage.as_view(), name='mainpage'),
    path('docs/', include('docs.urls')),
    path('contact/', include('contact.urls')),
    path('project/', include('project.urls')),
    path('report/', include('report.urls')),
    path('sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.urls import path

import docs.views

app_name = 'docs'
urlpatterns = [
    path('raisers', docs.views.Raisers.as_view(), name='raisers'),
    path('traders', docs.views.Traders.as_view(), name='traders'),
    path('donors', docs.views.Donors.as_view(), name='donors'),
    path('bitcoin-ethereum', docs.views.BitcoinEthereum.as_view(), name='bitcoin-ethereum'),
    path('rules', docs.views.Rules.as_view(), name='rules'),
    path('contract', docs.views.Contract.as_view(), name='contract'),
    path('charter', docs.views.Charter.as_view(), name='charter'),
    path('misc', docs.views.Misc.as_view(), name='misc'),
    path('help', docs.views.Help.as_view(), name='help'),
    path('privacy-policy', docs.views.Privacy.as_view(), name='privacy'),
    path('editorial-guidelines', docs.views.EditorialGuidelines.as_view(), name='editorial-guidelines'),
    path('team', docs.views.Team.as_view(), name='team'),
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'
urlpatterns = [
    path('crypto-affiliate', CryptoAffiliate.as_view(), name='crypto-affiliate'),
    path('ebook-form', EbookView.as_view(), name='ebook-form'),
    path('subscribe-simple', SubscribeView.as_view(), name='subscribe-simple'),
    path('test', TestView.as_view(), name='test')
]

project/urls.py
from django.urls import path, re_path

import project.views

app_name = 'project'
urlpatterns = [
    path('create', project.views.Create.as_view(), name='create'),
    re_path(r'edit/(\d+)', project.views.Edit.as_view(), name='edit'),
    path(r'seo/<int:project_pk>', project.views.SEOView.as_view(), name='seo'),
    re_path(r'view/(\d+)', project.views.Show.as_view(), name='view'),
    re_path(r'view-old/(\d+)', project.views.OldShow.as_view(), name='view-old'),
    re_path(r'activity/(\d+)', project.views.ProjectActivity.as_view(), name='activity'),
    path('list', project.views.List.as_view(), name='list'),
    path('feed', project.views.LatestProjectsMainFeed(), name='feed'),
    path('feed-investments', project.views.LatestProjectsInvestmentsFeed(), name='feed-investments'),
    re_path(r'withdraw/(\d+)', project.views.Withdraw.as_view(), name='withdraw'),
    # re_path(r'change-owner/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),
    re_path(r'change-owner2/(\d+)', project.views.ChangeOwner.as_view(), name='change-owner'),  # make URL different
]

user/urls.py
from django.urls import path, re_path

import user.views

app_name = 'user'
urlpatterns = [
    path('register', user.views.Register.as_view(), name='register'),
    path('account', user.views.Account.as_view(), name='account'),
    path('amounts', user.views.Amounts.as_view(), name='amounts'),
    re_path(r'profile/(\d+)', user.views.ViewProfile.as_view(), name='profile'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
import bleach
from django.conf import settings
from django.contrib import messages
from django.contrib.sitemaps import Sitemap
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.views.generic import View

from contact.forms import ContactForm
from main.form import EbookForm
from project.models import Project, ProjectVersion
from user.models import User, Subscriber


class MainPage(View):
    def get(self, request):
        contact_form = ContactForm()
        contact_form.fields['from_email'].widget.attrs['class'] = 'form-control'
        contact_form.fields['from_email'].widget.attrs['placeholder'] = 'Email Address*'
        contact_form.fields['subject'].widget.attrs['class'] = 'form-control'
        contact_form.fields['subject'].widget.attrs['placeholder'] = 'Topic*'
        contact_form.fields['text'].widget.attrs['class'] = 'form-control'
        contact_form.fields['text'].widget.attrs['placeholder'] = 'Write Message*'

        projects = Project.objects.filter(disabled=False).order_by('-pk')[:15]
        versions = []
        for p in projects:
            v = p.last_version()
            # v.short_description = mark_safe(bleach.clean(v.description[:540], strip=True,
            #                                              tags=['i', 'b', 'em', 'strong', 'a']))
            v.short_description = mark_safe(bleach.clean(v.description, strip=True,
                                                         tags=['i', 'b', 'em', 'strong', 'a']))
            v.short_description = mark_safe(bleach.clean(v.short_description[:100], strip=True,
                                                         tags=['i', 'b', 'em', 'strong', 'a']))
            versions.append(v)


        return render(request, 'main/mainpage.html', {'contact_form': contact_form,
                                                      'versions': versions})


class CryptoAffiliate(View):
    def get(self, request):
        return render(request, 'main/trade-crypto.html')


class SubscribeView(View):
    def post(self, request):
        try:
            email = request.POST['email']
        except KeyError:
            messages.add_message(request, messages.ERROR, 'Enter email.')
            return redirect('mainpage')
        try:
            obj, created = Subscriber.objects.get_or_create(email=email, subscribed=True, subscribed_projects=True)
        except IntegrityError:
            messages.add_message(request, messages.ERROR, 'Wrong email.')
            return redirect('mainpage')
        if not created:
            obj.subscribed = True
            obj.subscribed_projects = True
            obj.save()
        return redirect('mainpage')


class EbookView(View):
    def get(self, request):
        form = EbookForm(initial={'subscribed': True})
        return render(request, 'main/ebook-form.html', {'form': form})

    def post(self, request):
        form = EbookForm(request.POST)
        form.full_clean()
        if form.is_valid():
            form.save()
            return redirect('https://www.smashwords.com/books/view/947743')
        return render(request, 'main/ebook-form.html', {'form': form})


class MySitemap(Sitemap):
    protocol = settings.PROTOCOL

    # def get_urls(self, site=None, **kwargs):
    #     site = Site(domain=settings.DOMAIN, name=settings.DOMAIN)
    #     return super().get_urls(site=site, **kwargs)


class StaticViewSitemap(MySitemap):
    priority = 1.0

    def items(self):
        return ['mainpage',
                'main:crypto-affiliate', 'main:ebook-form',
                'project:feed',
                'project:feed-investments',
                'docs:raisers',
                'docs:traders',
                'docs:donors',
                'docs:rules',
                'docs:contract',
                'docs:charter',
                'docs:misc',
                'docs:help',
                'docs:privacy',
                'docs:editorial-guidelines',
                'docs:team']

    def location(self, item):
        return reverse(item)


class ProjectSitemap(MySitemap):
    priority = 1.0

    def items(self):
        return Project.objects.filter()

    def lastmod(self, obj):
        return obj.updated


class ProjectVersionSitemap(MySitemap):
    priority = 0.3

    def items(self):
        return ProjectVersion.objects.filter()

    def lastmod(self, obj):
        return obj.created


class UserSitemap(MySitemap):
    priority = 0.5

    def items(self):
        return User.objects.filter()


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class TestView(View):
    def get(self, request):
        return HttpResponse(get_client_ip(request))

main/templates/main/base.html
{% load bootstrap3 %}
{% load static %}

{% comment %}
{% block adkeywords %}nonprofit,nonprofits,crowdfunding,crowdfund,donation{% endblock %}
{% endcomment %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <base href="{% static 'newdesign/' %}"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>CryptoNGO - {% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="{% static 'favicon32x32.png' %}">
    <!-- All STYLESHEET CSS -->
    {% bootstrap_css %}
    {# TODO: Don't load Juery UI for pages not requiring it. #}
    <link rel='stylesheet' type='text/css' href='{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.css' %}'/>
    <link rel="stylesheet" href="css/element.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/responsive.css">
    <link rel="stylesheet" href="css/custom.css">
    <script src="js/vendor/jquery-1.12.0.min.js"></script>
    <script src="js/vendor/modernizr-2.8.3.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
    <style>
        button[disabled], input[type=button][disabled] {
            color: gray
        }

        .my-radio-widget {
            display: inline-block;
            margin-bottom: 0;
            padding-bottom: 0
        }

        .popup {
            background: white;
            max-width: 20em;
            border: 1px solid black;
            padding: 0.5ex;
        }

        .popup-link {
            text-decoration-style: dashed ! important;
            text-decoration-line: underline;
        }

        .required th label::after {
            content: "*";
        }

        .errorlist {
            color: red
        }

        td, th {
            padding: 2px;
            border: 1px solid #eee
        }

        .layout td, .layout th {
            padding: 0;
            border: none
        }

        input[type=text], input[type=url], input[type=number] {
            width: 100%
        }

        form td > ul, form td > div > ul {
            list-style: none;
            padding-left: 0px
        }

        {% block css %}{% endblock %}
    </style>
    {% block scripts %}{% endblock %}
    {% block moreheader %}{% endblock %}
</head>

<body>
<!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
<!-- Start Preloader -->
<!--preloader start-->
<div class="preloader">
    <div class="preloader-wrapper">
        <div class="preloader-img">
            <img src="img/preloader.png" alt="Preloader Image">
        </div>
    </div>
</div>
<!--preloader end-->
<!-- End Preloader -->
<!-- Start Main Wrapper -->
<div class="main-wrapper">
    <!-- Start Header Section -->
    <header>
        <nav>
            {% include 'main/top-header.html' %}
            <div class="header-area header-style-multipage stricky">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-2">
                            <div class="logo">
                                <a href="/"> <img src="img/logo.png" alt=""></a>
                            </div>
                        </div>
                        <div class="col-md-9 col-sm-10 main-menu-wrapper">
                            <div class="multipage-wrapper">
                                <ul class="main-menu">
                                    {% include 'main/menu.html' %}
                                </ul>
                                {#                            <div class="search-option">#}
                                {#                                <ul>#}
                                {#                                    <li><a href="cry-token.html#" class="search-button"><i class="fa fa-search"></i></a>#}
                                {#                                        <ul>#}
                                {#                                            <li>#}
                                {#                                                <input class="form-control" name="name" type="text" placeholder="SEARCH"#}
                                {#                                                       required>#}
                                {#                                            </li>#}
                                {#                                        </ul>#}
                                {#                                    </li>#}
                                {#                                </ul>#}
                                {#                            </div>#}
                            </div>
                        </div>
                        <div class="mobile-menu-area">
                            <div class="mobile-menu">
                                <ul>
                                    {% include 'main/menu.html' %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-- End Header Section -->
    <!-- Start Banner Area -->
    <nav>
        <div class="banner-area banner-bg-4 ptb-120 bg-opacity-black-40">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="banner">
                            <h2>{% block shortheader %}{% endblock %}</h2>
                            <ul class="page-title-link">
                                <li><a href="/">Home</a></li>
                                {% block breadcrumbs %}{% endblock %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- End Banner Area -->
    <!-- Start Main Content Wrapper -->
    <div class="main-content-wrapper">
        {# FIXME: not clickable #}
        <nav class="text-right">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_inline_share_toolbox"
                 style="margin-top: 4px; margin-left: 0.3em; z-index: 10000"></div>
        </nav>
        <div class="content-section-area ptb-100 bg-service cry">
            <div class="container" style="margin-top:60px;">
                <div class="row">
                    <div class="service-wrapper">
                        <div class="col-md-12">
                            <div class="service-text">
                                <div class="service-wrapper">
                                    <div class="col-md-12" style="margin-bottom:10px;">
                                        <div class="service-text">
                                            {% bootstrap_messages %}
                                            <h2>{% block header %}{% endblock %}</h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Start About Text Section -->
        <div class="content-section-area ptb-100 bg-service cry">
            <div class="container">
                <div class="row">
                    <div class="service-wrapper">
                        <div class="col-md-12">
                            <div class="service-text">
                                <div class="service-wrapper">
                                    <div class="col-md-12" style="margin-bottom:10px;">
                                        {% block content %}{% endblock %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Start Footer Section -->
                <div class="clearfix"></div>

                <!-- Start Footer Section -->
                <!-- End Main Content Wrapper -->
            </div>
        </div>

    </div>
    {% include 'main/footer.html' %}
</div>

{% include 'main/end.html' %}
{% block scripts2 %}{% endblock %}

</body>
</html>

main/templates/main/ebook-form.html
{% extends "main/base.html" %}

{% block moreheader %}<meta name="robots" content="noindex" />{% endblock %}
{% block title %}Download ebook{% endblock %}
{% block header %}Download ebook{% endblock %}
{% block shortheader %}Ebook{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'main:ebook-form' %}">Ebook</a></li>
{% endblock %}

{% block content %}
{# <div id="dialog" title="Download ebook" style="display: none"> #}
    <p>Fill the form for free entertaining ebook download.</p>
    <form method="post" action="{% url 'main:ebook-form' %}" target="_blank" class="dialog-form">
        {% csrf_token %}
        <table>
            <col style="width:15em" />
            {{ form }}
        </table>
        <p><input type="submit" value="Download"></p>
    </form>
{# </div> #}
{% endblock %}

main/templates/main/end.html
{% load static %}
{% load bootstrap3 %}
<script src="js/plugins.js"></script>
<script src="js/instafeed.html"></script>
<script src="js/main.js"></script>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script async type="text/javascript"
        src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5cfd1ca0e144ec14"></script>
{{ googlytics_code }}
{% bootstrap_javascript %}
<script type='text/javascript' src='{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.js' %}'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
<script src="{% static 'main.js' %}"></script>

<nav id="no_web3_warning"
     style="display: none; position: fixed; bottom: 0px; background: red; color: white; text-align: center; padding: 3px">
    Non-Ethereum browser detected. You should consider trying
    <a href="https://metamask.io" target="_blank" style="color: #0ff">MetaMask</a>.
    <span aria-hidden="true"
          onclick="$('#no_web3_warning').remove()"
          style="font-weight: bold; font-size: larger; cursor: pointer">&times;</span>
</nav>

main/templates/main/errors.html
{% if form.errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

main/templates/main/footer.html
<div class="clearfix"></div>
<footer>
    <nav>
        <div class="footer-widget-area ptb-100 footer-weve ">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6">
                        <div class="footer-widget-item">
                            <div class="logo footer-logo">
                                <a href="/"><img src="img/footer.png" alt=""></a>
                            </div>
                            <p>This entire project is run
                                by a skilled cryptocurrency
                                enthusiast who is passionate
                                about helping worthy
                                non-profit projects receive
                                the funding they deserve.</p>
                            <ul class="widget-address">
                                <li><a href="#" onclick="return false"><i class="fa fa-map-marker m-5"></i> Shay Agnon
                                    32-29,
                                    Ashkelon, Israel</a></li>
                                <li><a href="mailto:porton@narod.ru"><i class="fa fa-envelope m-5"></i> porton@narod.ru</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6">
                        <div class="footer-widget-item">
                            <h4>USEFUL LINKS</h4>
                            <ul class="widget-link">
                                {% include 'main/menu.html' with in_footer=True %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6">
                        <div class="footer-widget-item">
                            <h4>NEWSLETTER SIGNUP</h4>
                            <div class="form-subscribe">
                                <form method="post" action="{% url 'main:subscribe-simple' %}">
                                    {% csrf_token %}
                                    <input class="form-control" type="email" placeholder="Subscribe Now" name="email">
                                    <button class="submit" href="#" style="border: 0">
                                        <i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                </form>
                            </div>
                            <h4>Footer Social</h4>
                            <ul class="social-bookmarkas">
                                <li><a href="https://www.facebook.com/crypto4ngo/"><i class="ti-facebook"></i></a></li>
                                <li><a href="https://twitter.com/crypto4ngo"><i class="ti-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/23718851/"><i class="ti-linkedin"></i></a>
                                </li>
                                <li><a href="https://www.youtube.com/channel/UCtIa80EJ5J9kaKxJ7Wa9Fmw"><i
                                        class="ti-youtube"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-top: 3ex">
                    <p>Syndicate: <a href="{% url 'project:feed' %}">Projects RSS</a> |
                        <a href="{% url 'project:feed-investments' %}">Projects RSS (investments)</a> |
                        <a href="https://crypto4ngo.org/blog/feed/">Blog RSS</a> ||
                        <a href="{% url 'main:ebook-form' %}">Free entertaining ebook download</a></p>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="row">
                    <div class="copyright">
                        <p>Copyright 2019 &copy; <a href="/">CryptoNGO</a>. All Rights
                            Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</footer>

main/templates/main/menu.html
<li><a href="/">{% if in_footer %}<i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}Home</a></li>
<li><a href="{% url 'project:list' %}">{% if in_footer %}
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}Projects</a></li>
<li><a href="{% url 'project:create' %}">{% if in_footer %}
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}Add project</a></li>
<li><a href="#" onclick="return false">{% if in_footer %}<i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}Docs <b
        class="caret"></b></a>
    <ul>
        <li><a href="{% url 'docs:raisers' %}">For money raisers</a></li>
        <li><a href="{% url 'docs:traders' %}">For investors/traders</a></li>
        <li><a href="{% url 'docs:donors' %}">For donors</a></li>
        <li><a href="{% url 'docs:bitcoin-ethereum' %}">Crypto Crowdfunding</a></li>
        <li role="separator" class="divider"></li>
        <li>
            <a href="https://crypto4ngo.org/blog/2019/07/frequently-asked-questions/">FAQ</a>
        </li>
        <li>
            <a href="https://crypto4ngo.org/blog/2019/07/cryptongo-cry-token-white-paper/">Whitepaper</a>
        </li>
        <li role="separator" class="divider"></li>
        <li><a href="#" onclick="return false">About &raquo;</a>
            <ul>
                <li><a href="{% url 'docs:help' %}">Help</a></li>
                <li><a href="{% url 'docs:rules' %}">Rules</a></li>
                <li><a href="{% url 'docs:charter' %}">Charter</a></li>
                <li><a href="{% url 'docs:misc' %}">Misc</a></li>
                <li><a href="{% url 'docs:privacy' %}">Privacy policy</a></li>
                <li><a href="{% url 'docs:editorial-guidelines' %}">Editorial guidelines</a></li>
                <li><a href="{% url 'docs:team' %}">Team</a></li>
            </ul>
        </li>
    </ul>
</li>
<li><a href="/blog/">{% if in_footer %}<i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}Blog</a></li>
<li><a href="#" onclick="return false">{% if in_footer %}<i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}Support <b
        class="caret"></b></a>
    <ul>
        <li><a href="/forum/">Forums</a></li>
        <li><a href="{% url 'contact:contact' %}" rel="nofollow">Contact us</a></li>
{#        <li><a href="https://search.google.com/local/writereview?placeid=">Review us</a></li>#}
    </ul>
</li>
<!--li><a href="{% url 'project:view' 1 %}"
       style="text-decoration:underline;color:#337ab7;">{% if in_footer %}
    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>{% endif %}CRY Token</a></li-->

main/templates/main/paginator_template.html
{% load link_name %}
{% load proper_paginate %}
{#% if is_paginated %#}
    {% load proper_paginate %}
    {% load link_name %}
    <ul class="pagination">
        {% if page_obj.number == 1 %}
            <li class="disabled"><span>⇤</span></li>
        {% else %}
            <li><a href={{ request.get_full_path|link_name:1 }}>⇤</a></li>
        {% endif %}
        {% if page_obj.has_previous %}
            <li><a href={{ request.get_full_path|link_name:page_obj.previous_page_number }}>&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator|proper_paginate:page_obj.number %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href={{ request.get_full_path|link_name:i }}>{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href={{ request.get_full_path|link_name:page_obj.next_page_number }}>&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
        {% if page_obj.number == paginator.num_pages %}
            <li class="disabled"><span>⇥</span></li>
        {% else %}
            <li><a href={{ request.get_full_path|link_name:paginator.num_pages }}>⇥</a></li>
        {% endif %}
    </ul>
{#% endif %#}

main/templates/main/top-header.html
<div class="header-top">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="header-top-left">

                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="header-top-right">
                    <ul class="info-login">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'user:account' %}" rel="nofollow"
                                   rel="nofollow"><i class="fa fa-user" aria-hidden="true"></i> Account</a>
                            <li><a href="{% url 'logout' %}" rel="nofollow"
                                   rel="nofollow"><i class="fa fa-sign-out" aria-hidden="true"></i> Log out</a>
                                {% else %}
                            <li><a href="{% url 'login' %}?next={{ request.path }}" rel="nofollow"
                                   rel="nofollow"><i class="fa fa-user" aria-hidden="true"></i> Login</a>
                            </li>
                            <li><a href="{% url 'user:register' %}" rel="nofollow"><i class="fa fa-sign-in"
                                                                                      aria-hidden="true"></i>
                                Sign
                                Up</a></li>
                        {% endif %}
                        <li class="buy"><a target="_blank" rel="nofollow"
                                           href="https://www.coinmama.com/?cxd=57420_489863&affid=57420"
                                           rel="nofollow">Buy/Sell
                            Crypto</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>